image:
  repository: jaimehenao8126/argocd-monitor
  tag: 0.1.1
  pullPolicy: IfNotPresent
schedule: "0 */1 * * *"
config:
  argoNamespace: argocd
  maxRetries: 5
  retryInterval: 60
  progressingTimeout: 300
  slackWebhookUrl: "" # Â¡El usuario debe proporcionar esto!
rbac:
  create: true
  serviceAccountName: argocd-monitor-sa
resources: {}
